services:
  app:
    build: .
    environment:
      - DB_ADDRESS=db
      - DB_PORT=3306
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASENAME=${DB_DATABASENAME}
    depends_on:
      - db
    container_name: app
  db:
    image: "mariadb:10.7.4"
    environment:
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=${DB_DATABASENAME}
    container_name: db
  web:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/templates
    ports:
      - "80:80"
    environment:
      - APP_ADDRESS=app
    container_name: web
    depends_on:
      - app
      - db

    